### ISSUE TITLE
Занятие 4.04.16

### ISSUE THREAD

**Issue by malinovsky239** [CSC-MobDev-2016/lesson6#1]
Не придумал, где ещё задать этот вопрос, поэтому задаю здесь.
Будет ли завтра занятие (его нет в календаре CS центра, отсюда и сомнения) и, если да, во сколько оно начнётся? (иными словами, будет ли на нём коллоквиум?)

**Comment by thevery** [comment]
Будет обычное занятие, на сайт добавлю.

**Comment by thevery** [comment]
Добавил.
