### ISSUE TITLE
Удаленное написание коллоквиума

### ISSUE THREAD

**Issue by fedorovr** [CSC-MobDev-2016/lesson6#19]
Не знаю, как написать вам лично, поэтому пишу здесь
Завтра у меня образовалась встреча с научным руководителем и мини-отчет перед зав кафедры в Петергофе в 17ч, возможно ли написать коллоквиум дистанционно?

**Comment by thevery** [comment]
Нет.
Для тех, кто не может завтра попробую устроить ещё одну сдачу в яндексе.
