### ISSUE TITLE
Уточнения по заданию

### ISSUE THREAD

**Issue by ppzhuk** [CSC-MobDev-2016/lesson6#7]
- Выбор цвета и отображение в списке (например, фоном)

Не могли бы вы пояснить этот пункт.
- Не забывайте про имя пакета, иконку и локализацию + параметры для EditText-а

Подразумевается, что иконка должна быть не стандартная? А если я рисовать не умею, содранная из интернета подойдет?

**Comment by thevery** [comment]
Стандартный генератор же есть в студии

**Comment by ppzhuk** [comment]
Ок, а что в первом пункте имеется в виду?

**Comment by thevery** [comment]
https://lh3.googleusercontent.com/YrjpGoaxi2N4SGUl1PebGSjZH1okAt1XoerFVOD9AFHskK7BJcxwfkjRxlE5wSIObTo=h310

Но это сложный вариант, можно начать с обычного ColorPicker-а

**Comment by thevery** [comment]
В целом суть в том, чтобы задать элементу из списка какой-нибудь цвет (а-ля визуальный тег).
