### ISSUE TITLE
Занятие на следующей неделе

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [CSC-MobDev-2016/lesson6#8]
Занятие уже точно будет во вторник? На той неделе вроде речь шла о понедельнике

**Comment by thevery** [comment]
Точно. В понедельник, увы, я совсем никак не могу :(

**Comment by AnastasiaSulyagina** [comment]
А что делать тем, кто совсем никак не может во вторник?

**Comment by thevery** [comment]
Для них постараюсь провести отдельный коллоквиум.

**Comment by AnastasiaSulyagina** [comment]
Может всем было бы проще на через неделю перенести?

**Comment by thevery** [comment]
Этот пропущенный понедельник всё равно никуда не денется, а со следующим пока тем более равно непонятно.

**Comment by AnastasiaSulyagina** [comment]
То есть есть вероятность, что теперь курс будет не по понедельникам?

**Comment by thevery** [comment]
Нет, но курс начинается в 20, а коллоквиум - в 19, те на час с лишним раньше.
